### ISSUE TITLE
Use wireui/heroicons for a more consistent looking iconset?

### ISSUE THREAD

**Issue by titonova** [mikebarlow/megaphone#31]
Checkout this package:

https://github.com/wireui/heroicons

It's an icon set library (decoupled from it's parent package, WireUI), I am thinking maybe we can replace all the icons in the repo with it so that it would require much less code, be easier to manipulate and be more consistent all round.

Eg:

```
<button role="button" aria-label="close modal" class="focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 rounded-md cursor-pointer" @click="open = false">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M18 6L6 18" stroke="#4B5563" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
        <path d="M6 6L18 18" stroke="#4B5563" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
</button>
```
To:
`<button class="right-0"><x-icon name="x" class="w-6 h-6 text-gray-500" /></button>`

I want to make a pull request to do so btw.

@mikebarlow

**Comment by mikebarlow** [comment]
I'm familiar with heroicons, used it myself on a few projects before. I am tempted in this instance though to not use it (or any icon set for that matter). Mainly because it could potentially lead to forcing users to include heroicons into their project when they aren't using it. 

I think for Megaphone, I'm more tempted to simply split the SVG icons currently in use into their own files. That way it makes it easy for someone publish the views and simply drop in their own SVG or icon into the relevant blade file.
